### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by yosefromano** [adam-devapp/drupal-pantheon-civicrm-cache-clear#1]
I installed the module but it breaks the site. 
It complains that the mydb.civicrm_cache_clear table doesn't exist SELECT n.pid AS pid, n.currentpath AS currentpath
FROM 
{civicrm_cache_clear} n
ORDER BY pid DESC; Array
(
)

**Comment by adam-devapp** [comment]
Work around is running SQL manually:

CREATE TABLE `civicrm_cache_clear` (
  `pid` int(10) UNSIGNED NOT NULL COMMENT 'The primary identifier',
  `currentpath` text NOT NULL COMMENT 'Current template path'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by yosefromano** [comment]
Problem was that I was testing on my local environment. When I pushed the module to Pantheon and enabled it, it worked fine.

**Comment by adam-devapp** [comment]
Welcome hope it helps. Yes wasn't able to replicate. Installed fine on install. Will close.

**Comment by guyoron** [comment]
I think this is actually an issue, at least if `civicrm_entity` module is present. What happens, during your module install, is that drupal loads the .module file and the .install file, then tries to install the schema. It calls your `hook_schema`, and then it invokes all the `hook_schema_alter()`s. One of those is `civicrm_entity_schema_alter()`, which in turn calls the internal function `_civicrm_entity_enabled_entities`, which, long story short, ends up calling your `civicrm_cache_clear_civicrm_config()` (because your .module has been loaded), which expects the db table to exist, which it doesn't yet because all this is happening in the schema install process.

As far as I can tell this means that installing this module should always result in an error on a site that has `civicrm_entity` installed (though possibly there are some conditions in there to lead to this case, like the config cache needing to be cleared for some reason.

I've found some drupal core issues related to this, but nothing that's ready to be applied.

One solution could be to add a check to `civicrm_cache_clear_get_path()` to make sure the db table exists. Another, if you don't want an extra db call in there, would be to set a `civicrm_cache_clear_initialized` after the moduleis successfully enabled, and check that in `civicrm_cache_clear_get_path()`. 

It does seem like a bit of an unfortunate thing to have to add to your module just for the install process, but I don't really see a better way. Maybe another way is to not use hook_schema, and instead run the table creation command manually in a `hook_install`.

Let me know if you're interested in fixing this and I can provide a pull request.
